name: Evaluation Service CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - feature/ci-ecr

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: fiap-tech-challenge-devops/reusable-workflows/.github/workflows/go-ci.yml@feature/ci-devsecops

    with:
      go-version: "1.21"
      ecr-repository: "togglemaster/evaluation-service"

    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}